In [ ]:
import pandas as pd

s = pd.Series([1, 3, 5, 7, 9])
print(s)
"""series são arrays unidimensionais que podem armazenar qualquer tipo de dados"""

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [4]:
data = {
    'Nome': ['Ana', 'João', 'Maria'],
    'Idade': [25, 30, 35],
    'Cidade': ['SP', 'RJ', 'BH']
}

df = pd.DataFrame(data)
print(df)
"""dataframes são como uma tabela inteira, estrutura com linhas e colunas"""

# Primeiras linhas
df.head()

# Últimas linhas  
df.tail()

# Informações gerais
df.info()

# Estatísticas descritivas
df.describe()

    Nome  Idade Cidade
0    Ana     25     SP
1   João     30     RJ
2  Maria     35     BH
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nome    3 non-null      object
 1   Idade   3 non-null      int64
 2   Cidade  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

       Idade
count    3.0
mean    30.0
std      5.0
min     25.0
25%     27.5
50%     30.0
75%     32.5
max     35.0

In [15]:
# Selecionar coluna
df['Nome']

# Selecionar múltiplas colunas
df[['Nome', 'Idade']]

# Selecionar por índice
df.iloc[0]      # Primeira linha
df.loc[[0]]       # Primeira linha (por índice)

# Filtros
df[df['Idade'] > 30]

    Nome  Idade Cidade
2  Maria     35     BH

In [ ]:
# Adicionar coluna
df['Salário'] = [5000, 6000, 7000]

# Renomear colunas
df.rename(columns={'Nome': 'Nomes'})

# Ordenar dados
df.sort_values('Idade', ascending=False)

# Valores únicos
df['Cidade'].unique()
# Agrupar e calcular estatísticas

print(df)

    Nome  Idade Cidade  Salário
0    Ana     25     SP     5000
1   João     30     RJ     6000
2  Maria     35     BH     7000